brew "awscli"
brew "azure-cli"
brew "azure/functions/azure-functions-core-tools@4"
brew "bat"
brew "cmake"
brew "cocoapods"
brew "deno"
brew "dos2unix"
brew "fastfetch"
brew "ffmpeg"
brew "fzf"
brew "gemini-cli"
brew "genact"
brew "gh"
brew "git"
brew "go"
brew "gradle"
brew "hashicorp/tap/terraform"
brew "htop"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "mas"
brew "mono-libgdiplus"
brew "neovim"
brew "nkf"
brew "nvm"
brew "ollama"
brew "opencode"
brew "oven-sh/bun/bun"
brew "postgresql@17"
brew "protobuf"
brew "rbenv"
brew "redis"
brew "rustup"
brew "sqlcmd"
brew "sqlite"
brew "starship"
brew "tesseract"
brew "tree"
brew "uv"
brew "watchman"
brew "xmake"
brew "yq"
brew "zsh"
cask "android-studio"
cask "appcleaner"
cask "canva"
cask "copilot-cli"
cask "discord"
cask "docker-desktop"
cask "flutter"
cask "gcloud-cli"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "maccy"
cask "microsoft-teams"
cask "notion"
cask "pgadmin4"
cask "podman-desktop"
cask "powershell"
cask "temurin@17"
cask "unity-hub"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
mas "iMovie", id: 408981434
mas "Kindle", id: 302584613
mas "LINE", id: 539883307
mas "RunCat", id: 1429033973
mas "Swift Playground", id: 1496833156
mas "Windows App", id: 1295203466
mas "Xcode", id: 497799835
