brew "awscli"
brew "azure-cli"
brew "azure/functions/azure-functions-core-tools@4", trusted: true
brew "bat"
brew "boost"
brew "cmake"
brew "cocoapods"
brew "deno"
brew "dos2unix"
brew "fastfetch"
brew "ffmpeg"
brew "fzf"
brew "genact"
brew "gh"
brew "git"
brew "go"
brew "googleworkspace-cli"
brew "gradle"
brew "hashicorp/tap/terraform", trusted: true
brew "htop"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "llvm"
brew "mas"
brew "mono-libgdiplus"
brew "muter-mutation-testing/formulae/muter", trusted: true
brew "neovim"
brew "nkf"
brew "nvm"
brew "ollama"
brew "oven-sh/bun/bun", trusted: true
brew "postgresql@17"
brew "protobuf"
brew "rbenv"
brew "redis"
brew "ruby-build"
brew "rustup"
brew "sqlcmd"
brew "sqlite"
brew "starship"
brew "swiftformat"
brew "swiftlint"
brew "tesseract"
brew "tree"
brew "uv"
brew "watchman"
brew "xmake"
brew "yq"
brew "zsh"
cask "android-studio"
cask "antigravity-cli"
cask "appcleaner"
cask "balenaetcher"
cask "canva"
cask "claude-code"
cask "codex"
cask "claude"
cask "copilot-cli"
cask "dbeaver-community"
cask "discord"
cask "docker-desktop"
cask "flutter"
cask "font-hackgen-nerd"
cask "font-noto-sans-cjk-jp"
cask "font-roboto"
cask "gcloud-cli"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "maccy"
cask "mactex-no-gui"
cask "microsoft-teams"
cask "notion"
cask "powershell"
cask "temurin@17"
cask "unity-hub"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
mas "iMovie", id: 408981434
mas "Kindle", id: 302584613
mas "LINE", id: 539883307
mas "RunCat", id: 1429033973
mas "Swift Playground", id: 1496833156
mas "Windows App", id: 1295203466
mas "Xcode", id: 497799835
tap "azure/functions"
tap "hashicorp/tap"
tap "muter-mutation-testing/formulae"
tap "oven-sh/bun"
