format = """
[░▒▓](#a3aed2)\
[ 🍕 ](fg:#090c0c bg:#a3aed2)\
$os\
$shell\
[](fg:#5e7fc0 bg:#769ff0)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$git_state\
[](fg:#394260 bg:#1d2230)\
$cmd_duration\
$time\
[ ](fg:#1d2230)\
\n$character"""

[os]
disabled = false
style = "fg:#e3e5e5 bg:#5e7fc0"
format = "[ $symbol - ]($style)"

[os.symbols]
Windows = "Windows"

[shell]
disabled = false
style = "fg:#e3e5e5 bg:#5e7fc0"
format = '[$indicator$shlvl ]($style)'
pwsh_indicator = "pwsh"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[git_state]
style = "bg:#394260"
format = '[[($state($progress_current/$progress_total) )](fg:#769ff0 bg:#394260)]($style)'

[cmd_duration]
min_time = 2000
style = "fg:#a0a9cb bg:#1d2230"
format = "[ 󱎫 $duration ]($style)"
disabled = false

[time]
disabled = false
time_format = "%F %T.%3f"
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
