- bierner.markdown-mermaid
- chrmarti.regex
- DavidAnson.vscode-markdownlint
- dbaeumer.vscode-eslint
- EditorConfig.EditorConfig
- golang.go
- Gruntfuggly.todo-tree
- humao.rest-client
- mechatroner.rainbow-csv
- ms-azuretools.vscode-docker
- MS-CEINTL.vscode-language-pack-ja
- ms-dotnettools.csdevkit
- ms-dotnettools.csharp
- ms-dotnettools.dotnet-maui
- ms-dotnettools.vscode-dotnet-runtime
- ms-dotnettools.vscodeintellicode-csharp
- ms-vscode-remote.remote-wsl
- ms-vscode.cmake-tools
- ms-vscode.cpptools
- ms-vscode.cpptools-extension-pack
- ms-vscode.cpptools-themes
- ms-vscode.powershell
- ms-vsliveshare.vsliveshare
- msjsdiag.vscode-react-native
- oderwat.indent-rainbow
- PKief.material-icon-theme
- redhat.vscode-yaml
- ritwickdey.LiveServer
- rust-lang.rust-analyzer
- styled-components.vscode-styled-components
- tauri-apps.tauri-vscode
- techer.open-in-browser
- tomoki1207.pdf
- twxs.cmake
- VisualStudioExptTeam.intellicode-api-usage-examples
- VisualStudioExptTeam.vscodeintellicode
- yzane.markdown-pdf

