- ajhyndman.jslint
- amazonwebservices.aws-toolkit-vscode
- Angular.ng-template
- bierner.markdown-mermaid
- chrmarti.regex
- csstools.postcss
- DavidAnson.vscode-markdownlint
- eamodio.gitlens
- EditorConfig.EditorConfig
- eightHundreds.vscode-drawio
- formulahendry.vscode-mysql
- golang.go
- Gruntfuggly.todo-tree
- hediet.vscode-drawio
- ICS.japanese-proofreading
- jebbs.plantuml
- jtlowe.vscode-icon-theme
- ms-azuretools.vscode-docker
- MS-CEINTL.vscode-language-pack-ja
- ms-dotnettools.csharp
- ms-mssql.data-workspace-vscode
- ms-mssql.mssql
- ms-mssql.sql-bindings-vscode
- ms-mssql.sql-database-projects-vscode
- ms-python.isort
- ms-python.python
- ms-python.vscode-pylance
- ms-toolsai.jupyter
- ms-toolsai.jupyter-keymap
- ms-toolsai.jupyter-renderers
- ms-toolsai.vscode-jupyter-cell-tags
- ms-toolsai.vscode-jupyter-slideshow
- ms-vscode-remote.remote-containers
- ms-vscode-remote.remote-wsl
- ms-vscode.azure-account
- ms-vscode.azurecli
- ms-vscode.cmake-tools
- ms-vscode.cpptools
- ms-vscode.powershell
- ms-vsliveshare.vsliveshare
- msjsdiag.vscode-react-native
- oderwat.indent-rainbow
- redhat.vscode-yaml
- ritwickdey.LiveServer
- rust-lang.rust-analyzer
- styled-components.vscode-styled-components
- tauri-apps.tauri-vscode
- techer.open-in-browser
- tomoki1207.pdf
- twxs.cmake
- VisualStudioExptTeam.intellicode-api-usage-examples
- VisualStudioExptTeam.vscodeintellicode
- yzane.markdown-pdf

