- Id: 7zip.7zip
- Id: AgileBits.1Password
- Id: Amazon.AWSCLI
- Id: CubeSoft.CubePDF
- Id: gerardog.gsudo
- Id: Git.Git
- Id: GitHub.cli
- Id: GitHub.GitHubDesktop
- Id: GoLang.Go
- Id: Google.AndroidStudio
- Id: Google.Chrome
- Id: Google.CloudSDK
- Id: JesseDuffield.lazygit
- Id: junegunn.fzf
- Id: mbuilov.sed
- Id: Microsoft.Azure.FunctionsCoreTools
- Id: Microsoft.AzureCLI
- Id: Microsoft.OpenJDK.17
- Id: Microsoft.PowerAutomateDesktop
- Id: Microsoft.PowerShell
- Id: Microsoft.PowerToys
- Id: Microsoft.Sqlcmd
- Id: Microsoft.SQLServerManagementStudio
- Id: Microsoft.VisualStudio.2022.Professional
- Id: Microsoft.VisualStudioCode
  Options: "/VERYSILENT /NORESTART /MERGETASKS=!runcode,addcontextmenufiles,addcontextmenufolders,associatewithfiles,addtopath"
- Id: Microsoft.WindowsTerminal
- Id: MikeFarah.yq
- Id: OpenJS.NodeJS.LTS
- Id: Python.Python.3.12
- Id: raphamorim.rio
- Id: Rustlang.Rustup
- Id: Starship.Starship
- Id: stedolan.jq
- Id: UB-Mannheim.TesseractOCR
- Id: waterlan.dos2unix
- Id: WinMerge.WinMerge
- Id: WiresharkFoundation.Wireshark
- Id: Yarn.Yarn
- Id: Zoom.Zoom
