$schema: https://aka.ms/winget-packages.schema.1.0.json
WinGetVersion: 0.3.11201
Sources:
  - Packages:
      - Id: 7zip.7zip
      - Id: AgileBits.1Password
      - Id: Amazon.AWSCLI
      - Id: Amazon.SAM-CLI
      - Id: Canonical.Ubuntu
      - Id: MikeFarah.yq
      - Id: gerardog.gsudo
      - Id: Git.Git
      - Id: GitHub.cli
      - Id: GoLang.Go
      - Id: Google.Chrome
      - Id: JanDeDobbeleer.OhMyPosh
      - Id: Microsoft.AzureCLI
      - Id: Microsoft.MSIXPackagingTool
      - Id: Microsoft.PowerAutomateDesktop
      - Id: Microsoft.PowerShell
      - Id: Microsoft.PowerToys
      - Id: Microsoft.SQLServerManagementStudio
      - Id: Microsoft.VisualStudioCode
      - Id: Microsoft.WindowsTerminal
      - Id: NickeManarin.ScreenToGif
      - Id: OpenJS.NodeJS.LTS
      - Id: Rustlang.Rustup
      - Id: stedolan.jq
      - Id: WinMerge.WinMerge
      - Id: Yarn.Yarn
    SourceDetails:
      Argument: https://winget.azureedge.net/cache
      Identifier: Microsoft.Winget.Source_8wekyb3d8bbwe
      Name: winget
      Type: Microsoft.PreIndexed.Package
