$schema: https://aka.ms/winget-packages.schema.2.0.json
CreationDate: 2024-03-25T18:22:21.5270000+09:00
Sources:
  - Packages:
      - PackageIdentifier: 7zip.7zip
      - PackageIdentifier: AgileBits.1Password
      - PackageIdentifier: Amazon.AWSCLI
      - PackageIdentifier: Cisco.Webex
      - PackageIdentifier: CubeSoft.CubePDF
      - PackageIdentifier: Discord.Discord
      - PackageIdentifier: gerardog.gsudo
      - PackageIdentifier: Git.Git
      - PackageIdentifier: GitHub.cli
      - PackageIdentifier: GoLang.Go
      - PackageIdentifier: Google.AndroidStudio
      - PackageIdentifier: Google.Chrome
      - PackageIdentifier: Google.CloudSDK
      - PackageIdentifier: JesseDuffield.lazygit
      - PackageIdentifier: Logitech.OptionsPlus
      - PackageIdentifier: mbuilov.sed
      - PackageIdentifier: Microsoft.AzureCLI
      - PackageIdentifier: Microsoft.OpenJDK.17
      - PackageIdentifier: Microsoft.PowerShell
      - PackageIdentifier: Microsoft.PowerToys
      - PackageIdentifier: Microsoft.Sqlcmd
      - PackageIdentifier: Microsoft.SQLServerManagementStudio
      - PackageIdentifier: Microsoft.VisualStudio.2022.Professional
      - PackageIdentifier: Microsoft.VisualStudioCode
      - PackageIdentifier: Microsoft.WindowsTerminal
      - PackageIdentifier: MikeFarah.yq
      - PackageIdentifier: Notepad++.Notepad++
      - PackageIdentifier: OpenJS.NodeJS.LTS
      - PackageIdentifier: Python.Python.3.12
      - PackageIdentifier: Rustlang.Rustup
      - PackageIdentifier: Starship.Starship
      - PackageIdentifier: stedolan.jq
      - PackageIdentifier: UB-Mannheim.TesseractOCR
      - PackageIdentifier: waterlan.dos2unix
      - PackageIdentifier: WinMerge.WinMerge
      - PackageIdentifier: Yarn.Yarn
      - PackageIdentifier: Zoom.Zoom
    SourceDetails:
      Argument: https://cdn.winget.microsoft.com/cache
      Identifier: Microsoft.Winget.Source_8wekyb3d8bbwe
      Name: winget
      Type: Microsoft.PreIndexed.Package
WinGetVersion: 1.7.10661
