$schema: https://aka.ms/winget-packages.schema.2.0.json
CreationDate: 2024-03-25T18:22:21.5270000+09:00
Sources:
  - Packages:
      - PackageIdentifier: Cisco.Webex
      - PackageIdentifier: CubeSoft.CubePDF
      - PackageIdentifier: Logitech.OptionsPlus
      - PackageIdentifier: Microsoft.VisualStudio.2022.Professional
      - PackageIdentifier: Zoom.Zoom
    SourceDetails:
      Argument: https://cdn.winget.microsoft.com/cache
      Identifier: Microsoft.Winget.Source_8wekyb3d8bbwe
      Name: winget
      Type: Microsoft.PreIndexed.Package
WinGetVersion: 1.7.10661
