- Id: 7zip.7zip
- Id: AgileBits.1Password
- Id: Amazon.AWSCLI
- Id: Amazon.Kindle
- Id: 9PFHDD62MXS1 # Apple.Music
- Id: CubeSoft.CubePDF
- Id: Discord.Discord
- Id: gerardog.gsudo
- Id: Git.Git
- Id: GitHub.cli
- Id: GoLang.Go
- Id: Google.Chrome
- Id: Google.CloudSDK
- Id: JesseDuffield.lazygit
- Id: JGraph.Draw
- Id: Microsoft.Azure.FunctionsCoreTools
- Id: Microsoft.AzureCLI
- Id: Microsoft.DotNet.SDK.9
- Id: Microsoft.DotNet.SDK.8
- Id: Microsoft.DotNet.SDK.6
- Id: 9P1HQ5TQZMGD # Microsoft.Loop
- Id: Microsoft.OpenJDK.17
- Id: Microsoft.PowerAutomateDesktop
- Id: Microsoft.PowerShell
- Id: Microsoft.PowerToys
- Id: Microsoft.RemoteDesktopClient
- Id: Microsoft.SQLServerManagementStudio
- Id: 9NBLGGH5R558 # Microsoft.ToDo
- Id: Microsoft.VisualStudio.2022.Professional
- Id: Microsoft.VisualStudioCode
  Options: "/VERYSILENT /NORESTART /MERGETASKS=!runcode,addcontextmenufiles,addcontextmenufolders,associatewithfiles,addtopath"
- Id: Microsoft.WindowsTerminal
- Id: MikeFarah.yq
- Id: Logitech.OptionsPlus
- Id: OpenJS.NodeJS.LTS
- Id: Python.Python.3.12
- Id: raphamorim.rio
- Id: Starship.Starship
- Id: stedolan.jq
- Id: waterlan.dos2unix
- Id: WinMerge.WinMerge
- Id: WiresharkFoundation.Wireshark
- Id: Yarn.Yarn
- Id: Zoom.Zoom
